// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Categories(arg1) {
  return window['go']['main']['App']['Categories'](arg1);
}

export function Games(arg1) {
  return window['go']['main']['App']['Games'](arg1);
}

export function Get(arg1) {
  return window['go']['main']['App']['Get'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
