// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Categories(arg1:string):Promise<Array<number>>;

export function Games(arg1:string):Promise<Array<number>>;

export function Get(arg1:string):Promise<Array<number>>;

export function Greet(arg1:string):Promise<string>;
